### ISSUE TITLE
The link of "checkpoints" is unavailable.

### ISSUE THREAD

**Issue by demon02130101** [L-Medici/Rignet_blender_addon#1]
When I click the link "https://umass.box.com/s/l7dxfayrubf5qzxcyg7can715xnislwm", it tells me that "This shared file or folder link has been removed or is unavailable to you."

**Comment by L-Medici** [comment]
Hi there, try clicking on the link provided in https://github.com/zhan-xu/RigNet, maybe they have updated it somehow given it's their folder anyway
